se crea css de tercera pagina
Scar269/Ontas-bebe pull request #22
Opened 2024-08-07 21:56 UTC by mariomatos0

se crea css de tercera pagina y se modifica un poco el html para mejor función del mismo y se corrige linea 19 de  html de usuario

2024-08-07 22:03 UTC, JosuePlataV requested changes

2024-08-07 22:03 UTC, JosuePlataV commented on return.html
> +    <link rel="stylesheet" href="confirmacion.css"
No se agregó ningún  return.css al repo, favor de borrar la línea 7 o cambiar el nombre del archivo css vínculado y borrar la línea 8, se deja a elección del desarrollador.

2024-08-07 22:03 UTC, JosuePlataV commented on return.html
>          <button id="signOut" class="btn btn-primary">Cerrar sesión</button>
debido a que se borró bootstrap, la clase de este botón ya no es necesaria, favor de eliminarla.

2024-08-07 22:03 UTC, JosuePlataV commented on return.html
> +</html>
Falta dejar libre la última linea

2024-08-07 22:03 UTC, JosuePlataV commented on usuario.html
> +            <button id="goToReset">Compartenos tu ubicación</button></div>
Gracias por notar que nos faltó esto en el último PR

2024-08-07 22:03 UTC, JosuePlataV commented on return.html
> -</head>
Favor de agregar el cierre de head

2024-08-07 23:25 UTC, JosuePlataV requested changes

2024-08-07 23:25 UTC, JosuePlataV commented on return.html
> +            <p>Hemos enviado un correo electrónico a tu cuenta, en donde <br> encontrarás la información que compartiste con nosotros</p>
Favor de volver a agregar el botón, únicamente se tenía que borrar la clase del botón, no el botón entero

2024-08-08 00:23 UTC, JosuePlataV approved these changes
Todos los problemas resueltos

2024-08-08 01:37 UTC, Scar269 approved these changes
Todos los cambios requeridos han sido resueltos, no veo ningún problema en el código.

2024-08-08 01:37 UTC, Scar269 commented on return.html
> -<body class="page3">
¿Por qué se le agregó una clase a body? en el css no está incluida

2024-08-08 01:38 UTC, merged